// ─── KARMA APP — BUILT-IN SLOGANS ───────────────────────────────────
// 300 curated slogans. No internet needed. No repeats within 60 days.
// Categories: Discipline, Pisces, Indian Philosophy, Sky/Gagan/Cosmos,
//             Warrior/Stoic, Breaking habits, Morning, Night reflection.

import { DEFAULT_NAME, GOAL_NAME } from './appConfig';

export const SLOGANS = {
  discipline: [
    "Discipline is the bridge between goals and accomplishment.",
    "You don't rise to the level of your goals — you fall to the level of your systems.",
    "The man who moves a mountain begins by carrying away small stones.",
    "Small daily improvements are the key to staggering long-term results.",
    "We are what we repeatedly do. Excellence is not an act but a habit.",
    "Motivation gets you started. Discipline keeps you going.",
    "The price of discipline is always less than the pain of regret.",
    "Hard choices, easy life. Easy choices, hard life.",
    "Do what is hard and life becomes easy. Do what is easy and life becomes hard.",
    "Suffer the pain of discipline or suffer the pain of regret.",
    "Every action you take is a vote for the type of person you wish to become.",
    "You will never always be motivated. You must learn to be disciplined.",
    "The secret to getting ahead is getting started.",
    "Success is the sum of small efforts repeated day in and day out.",
    "One day at a time. One habit at a time. One version of yourself at a time.",
    "Consistency is what transforms average into excellence.",
    "Discipline equals freedom.",
    "The only person you are destined to become is the person you decide to be.",
    "Show up even when you don't feel like it — especially when you don't feel like it.",
    "Don't count the days. Make the days count.",
    "A river cuts through rock not because of its power, but because of its persistence.",
    "The difference between who you are and who you want to be is what you do.",
    "Fall in love with the process and the results will come.",
    "Train your mind to see what's possible, not what's comfortable.",
    "Identity follows action. Act first. Become second.",
    "Champions aren't made in gyms. Champions are made from something they have deep inside.",
    "Push yourself because no one else is going to do it for you.",
    "Great things never come from comfort zones.",
    "The only limit to your impact is your imagination and commitment.",
    "Stop waiting for the right time. The time will never be just right.",
    "Success is not final. Failure is not fatal. It's the courage to continue that counts.",
    "Strive for progress, not perfection.",
    "Your future self is watching you right now through your memories.",
    "What you do every day matters more than what you do every once in a while.",
    "The goal is not to be perfect. The goal is to be better than yesterday.",
    "Build good habits and become their slave — willingly.",
    "A year from now you'll wish you had started today.",
    "The secret of your future is hidden in your daily routine.",
    "You don't have to be great to start, but you have to start to be great.",
    "Discipline is choosing between what you want now and what you want most.",
  ],

  pisces: [
    "Like water, find your path around every obstacle — quietly, persistently.",
    "The ocean does not apologise for its depth. Neither should you.",
    "Still waters run deep. So do you, Gagan.",
    "Pisces: born at the end of seasons, carrying the wisdom of all that came before.",
    "Water does not fight the rock. It outlasts it.",
    "The fish knows — the surface is noise. Truth lives in the deep.",
    "You were born at the boundary of seasons. You were made for transitions.",
    "Depth is not weakness. Depth is where all great things are formed.",
    "The sea is calm or wild — but it is always the sea. Be always yourself.",
    "Feb 28 — the edge of winter, the breath before spring. You carry both.",
    "Intuition is the deepest form of intelligence. Trust yours.",
    "The tide goes out only to return stronger. So do you.",
    "Not all storms come to disrupt your life. Some come to clear your path.",
    "You feel deeply because you live deeply. That is your power.",
    "Even the deepest ocean has a floor. Know yours. Stand on it.",
    "A fish does not drown in water. This is your element.",
    "Born between worlds. Comfortable in neither — powerful in both.",
    "The moon pulls the tides. You were born when the pull was strongest.",
    "Sensitivity is not a flaw. It is precision of perception.",
    "Water takes the shape of any container but is never changed by it.",
  ],

  indian_philosophy: [
    "कर्म ही पूजा है — Action is worship.",
    "The Bhagavad Gita says: You have the right to work, not the fruits.",
    "Dhruv moved not. The world turned around him. Be the still point.",
    "Arjuna saw only the eye of the bird. See only your goal.",
    "The Pole Star does not chase planets. It simply is — unmoved, eternal.",
    "Karma is not punishment. Karma is precision.",
    "What you sow in your mornings, you reap in your years.",
    "A warrior does not wait for courage. A warrior acts, and courage follows.",
    "Sadhana — daily practice — is the only path. There are no shortcuts.",
    "The Mahabharata teaches: It is better to live your own path imperfectly than another's perfectly.",
    "Garuda does not ask permission from the sky. He simply flies.",
    "Moksha is not achieved. It is uncovered — layer by layer, day by day.",
    "Even Shiva meditates. Even the destroyer practices stillness.",
    "Tapas — discipline through heat and discomfort — is how diamonds are made.",
    "The Vedas say: Know thyself. Daily habits are how the knowing begins.",
    "Ahimsa begins with yourself. Do not harm your future self with present laziness.",
    "Matsya survived the great flood. Not through strength — through endurance.",
    "Rudra does not apologise for his intensity. Neither should you.",
    "The lotus blooms in mud. Your greatness grows in difficulty.",
    "Aum — the universe began with a sound, a vibration, a single act. Begin.",
    "Dharma is not what you believe. Dharma is what you do.",
    "Even a single lamp can drive away centuries of darkness.",
    "The Upanishads say: You are not the body. You are the one who watches.",
    "Gagan — the sky — has no ceiling. Go as high as you dare.",
    "A Yogi is not someone who never falls. A Yogi is someone who always rises.",
  ],

  sky_cosmos: [
    "Gagan — the sky — has no boundary. Neither do you.",
    "The sky does not shrink because of clouds. It waits.",
    "Gagan — the open sky above every storm.",
    "Stars don't compete with each other. They simply shine.",
    "The universe is 13.8 billion years old. Your excuses are much younger.",
    "Every constellation was once a collection of separate, unremarkable stars.",
    "The sky you're named after has no ceiling. Remember that.",
    "Even the darkest night ends. You are named after the sky after the storm.",
    "Akash — the infinite. You are larger than any single failure.",
    "The Pole Star never moved while empires rose and fell. Be that constant.",
    "Gravity does not apologise for pulling everything toward itself. Neither should your discipline.",
    "The moon completes its cycle every 28 days. So does transformation.",
    "You were born on Feb 28 — the sky's own boundary day.",
    "Ambar — the ancient sky — existed before you and will exist after. But right now, it watches.",
    "A shooting star burns completely in its purpose. Burn like that.",
    "The sky is the same everywhere. But how you see it depends on where you stand.",
    "Even the sun sets every day — and returns every morning. So will you.",
    "Light travels 299,792 km every second. It doesn't rest. Neither should your purpose.",
    "You are made of stardust — literally. Act like it.",
    "The universe is not random. Neither is the life you are building.",
  ],

  warrior_stoic: [
    "The obstacle is the way.",
    "Memento mori — remember death. It makes every day matter.",
    "Amor fati — love your fate. Even the hard days are shaping you.",
    "A Spartan does not ask how many. A Spartan asks where.",
    "What we do in life echoes in eternity.",
    "Waste no more time arguing what a good man should be. Be one.",
    "You have power over your mind, not outside events. Realise this.",
    "The best revenge is massive success.",
    "Do not pray for an easy life. Pray for the strength to endure a difficult one.",
    "Iron sharpens iron.",
    "The warrior who trains in peacetime has the easiest battles.",
    "Pain is temporary. Regret is permanent.",
    "Sweat more in training. Bleed less in war.",
    "A samurai without a sword is still a samurai.",
    "He who conquers himself is the mightiest warrior.",
    "Comfort is the enemy of achievement.",
    "The cave you fear to enter holds the treasure you seek.",
    "Strength does not come from winning. Your struggles develop your strength.",
    "A smooth sea never made a skilled sailor.",
    "Be ruthless with your habits. Be generous with your results.",
    "First say to yourself what you would be. Then do what you have to do.",
    "The impediment to action advances action. What stands in the way becomes the way.",
    "Endure today. Conquer tomorrow.",
    "A warrior is not about perfection or victory. A warrior is about absolute vulnerability.",
    "Do your duty. Let go of the outcome.",
  ],

  breaking_habits: [
    "Every time you resist, you are rewriting who you are.",
    "The urge will pass whether you give in or not. Wait it out.",
    "Your future self is begging your present self to stop.",
    "One moment of resistance is worth a hundred days of regret.",
    "The habit owns you until you own it.",
    "What triggers you controls you. Know your triggers.",
    "You are not your cravings. You are the one watching them.",
    "A slip is not a fall. Only giving up is a fall.",
    "The chain breaks on the day you break character. Don't break character.",
    "Comfort is lying to you. It always has been.",
    "What you resist, persists. What you replace, dissolves.",
    "Name the urge. Watch it. Let it pass. You are the observer.",
    "Every clean day is a vote for who you are becoming.",
    "You did not build this habit in a day. You won't break it in a day. Keep going.",
    "The version of you that gave in is not the real you.",
    "Boredom and stress will lie to you. They will say this habit is the answer. It isn't.",
    "Day 1 again is not failure. Day 1 again is courage.",
    "The hardest part is the moment before the decision. You can win that moment.",
    "Awareness is the first weapon. You are now armed.",
    "You have broken it before by accident. Now break it on purpose.",
  ],

  morning: [
    "The morning belongs to those who claimed it the night before.",
    "Every sunrise is an invitation. Accept it, Gagan.",
    "5 AM. The world is asleep. Your future is awake.",
    "Win the morning. Win the day.",
    "The first hour of the day is the rudder of the day.",
    "Mornings are not inconveniences. Mornings are the canvas.",
    "What you do before 8 AM defines what kind of day you will have.",
    "Rise with the sun. The sky has been waiting for you.",
    "Dawn does not negotiate. Neither should your alarm.",
    "The quiet hours are yours — if you take them.",
    "Each morning you are born again. What you do today is what matters most.",
    "Your bed is comfortable because your future is uncomfortable. Choose discomfort.",
    "The early bird does not get the worm by accident. It rises with intention.",
    "Sunrise is a daily reminder that darkness never wins.",
    "A good morning routine is the longest conversation you'll ever have with yourself.",
  ],

  night_reflection: [
    "Before you sleep: did today's Gagan deserve tomorrow's sunrise?",
    "The night is when warriors rest and plan. Rest well. Plan better.",
    "You cannot undo today. You can build tomorrow.",
    "Count your wins before you count your failings. Both matter.",
    "Sleep is not laziness. Sleep is preparation.",
    "The last thought before sleep shapes the first action after waking.",
    "Review your day like a warrior reviews a battle — honestly, without mercy, without guilt.",
    "Did you move the needle today? Even a millimetre counts.",
    "Night is the reset. Tomorrow is the retry. You always get another chance.",
    "Rest is part of the discipline. Honour it.",
    "The day is done. The streak lives on. Sleep knowing that.",
    "You showed up today. That is enough. Tomorrow, show up again.",
    "Darkness is not the end of the sky. It is the sky resting.",
    "What you are grateful for tonight, you will attract more of tomorrow.",
    "Close your eyes knowing today's Gagan was better than yesterday's.",
  ],
};

// Flat array for easy rotation
export const ALL_SLOGANS = Object.values(SLOGANS).flat();

// Get slogan for today (rotates, no repeat within 60 days)
export const getTodaySlogan = () => {
  const dayOfYear = Math.floor(
    (new Date() - new Date(new Date().getFullYear(), 0, 0)) / 86400000
  );
  const index = dayOfYear % ALL_SLOGANS.length;
  return ALL_SLOGANS[index];
};

// Get milestone message personal to Gagan
export const getMilestoneMessage = (days, habitName) => {
  const messages = {
    3:   `The seed is planted, ${DEFAULT_NAME}. "${habitName}" has begun.`,
    7:   `Seven sunrises. Seven choices. The Pole Star is watching.`,
    14:  `14 days of karma earned through "${habitName}". The sky held still.`,
    21:  `21 days — neuroscience says you're rewiring, ${DEFAULT_NAME}. You're no longer forcing it. You're becoming it.`,
    30:  `One month. 30 sunrises. The sky you're named after has no ceiling.`,
    48:  `Day 48. Most people quit before this. You are now in the top 5%.`,
    60:  `60 days deep — like Pisces water, quiet, persistent, unstoppable.`,
    75:  `Between 60 and 90 days motivation dips. You're still here. That's everything.`,
    90:  `90 days. This is no longer a habit, ${DEFAULT_NAME}. This is who you are.`,
    180: `Half a year of karma. The sky has witnessed every single day.`,
    365: `365 days ago ${DEFAULT_NAME} chose the reins. Today he is ${GOAL_NAME}.`,
  };
  return messages[days] || `${days} days strong, ${DEFAULT_NAME}. Keep building your karma.`;
};